/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2014-09-18 13:39:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Semana04;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import beans.BD;
import javax.swing.JOptionPane;
import java.sql.SQLException;

public final class Produto_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Tabelinha de preços</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<font face=\"calibri\" size=\"5px\">\r\n");
      out.write("\t\t<p>Produtos</p> ");

 	int cod;
 	String descricao;
 	String marca;
 	float estoque;
 	float preco;

 	String sql = "select * from produto";

 	BD bd = new BD();
 	try {
 		bd.getConnection();
 		bd.st = bd.con.prepareStatement(sql);
 		bd.rs = bd.st.executeQuery();

 		out.print("<table border=1 cellspacing=0>");
 		out.print("<tr bgcolor='orange'>");
 		out.print("<th>cod_produto</th><th>Descrição</th><th>Marca</th><th>Estoque</th><th>Preço</th></tr>");

 		while (bd.rs.next()) {

 			cod = bd.rs.getInt("cod_produto");
 			descricao = bd.rs.getString("descricao");
 			marca = bd.rs.getString("marca");
 			estoque = bd.rs.getFloat("estoque");
 			preco = bd.rs.getFloat("preco");

 			out.print("<tr><td width=50>" + cod + "</td>");
 			out.print("<td width=50>" + descricao + "</td>");
 			out.print("<td width=50>" + marca + "</td>");
 			out.print("<td width=50>" + estoque + "</td>");
 			out.print("<td width=50>" + preco + "</td></tr>");

 		}

 	} catch (SQLException err) {
 		JOptionPane.showMessageDialog(null, "Ocorreu um erro." + err);
 	} finally {
 		bd.Close();
 	}
 
      out.write("\r\n");
      out.write("\t\t<form action=\"Produto.jsp\" method=\"get\">\r\n");
      out.write("\t\t\t<input type=\"radio\" name=\"tipo\" value=\"cod\">Código <input\r\n");
      out.write("\t\t\t\ttype=\"radio\" name=\"tipo\" value=\"nome\">Descricao<br> <input\r\n");
      out.write("\t\t\t\ttype=\"text\" value=\"descricao\">\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t</font>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
