/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2014-09-18 19:58:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.SQLException;
import banco.BDSQL;

public final class exe03_005fvisualizacao_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Status</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");

		BDSQL bdsql = new BDSQL();

		String sql1 = "select * from bancario where cliente=? and operacao=?";
		//String sql2 = " select SUM (valor) as SOMA_DE_TODOS_CREDITOS from bancario where operacao='CREDITO' and cliente=?";
		//String sql3 = " select SUM (valor) as SOMA_DE_TODOS_DEBITOS from bancario where operacao='CREDITO' and cliente=?";

		String c = request.getParameter("cliente");
		String op = request.getParameter("operacao");
		
		int c1 = Integer.parseInt(c);
				try{
				bdsql.getConnection();
				bdsql.st = bdsql.con.prepareStatement(sql1);
				bdsql.st.setInt(1,c1);
				bdsql.st.setString(2, "operacao");

				bdsql.rs = bdsql.st.executeQuery();

				out.print("<table border=1 cellspacing=0>");
				out.print("<tr bgcolor='orange'>");
				out.print("<th>Numero</th><th>Cliente</th><th>Operação</th><th>Valor</th></tr>");

				while (bdsql.rs.next()) {

					int numero = bdsql.rs.getInt("numero");
					int cli = bdsql.rs.getInt("cliente");
					String operador = bdsql.rs.getString("operacao");
					float v = bdsql.rs.getFloat("valor");

					out.print("<tr><td width=50>" + numero + "</td>");
					out.print("<td width=50>" + cli + "</td>");
					out.print("<td width=50>" + operador + "</td></tr>");
					out.print("<td width=50>" + v + "</td></tr>");

				}
			} catch (SQLException e) {
				out.print("<p> Ocorreu um erro.</p>");

				out.print("<p>" + e.toString() + "</p>");

			} finally {
				bdsql.close();
			}	
		
	
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
